# development:
#   adapter: mysql2
#   encoding: utf8
#   database: c9
#   username: <%=ENV['C9_USER']%>
#   host: <%=ENV['IP']%>
  
# production:
#   adapter: postgresql
#   encoding: utf8

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5